"""Initial schema: all tables

Revision ID: 5edae6c9e964
Revises: 
Create Date: 2026-01-27 20:28:20.334182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5edae6c9e964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('persona_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('hero_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('mmr_bracket', sa.SmallInteger(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'role', 'patch_id', 'mmr_bracket', name='uq_hero_baseline')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.SmallInteger(), nullable=False),
    sa.Column('lobby_type', sa.SmallInteger(), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.Column('avg_mmr', sa.Integer(), nullable=True),
    sa.Column('replay_url', sa.Text(), nullable=True),
    sa.Column('replay_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('match_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'steam_id', name='uq_analysis_match_user')
    )
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=True),
    sa.Column('player_slot', sa.SmallInteger(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('gpm', sa.Integer(), nullable=True),
    sa.Column('xpm', sa.Integer(), nullable=True),
    sa.Column('last_hits', sa.Integer(), nullable=True),
    sa.Column('denies', sa.Integer(), nullable=True),
    sa.Column('hero_damage', sa.Integer(), nullable=True),
    sa.Column('tower_damage', sa.Integer(), nullable=True),
    sa.Column('hero_healing', sa.Integer(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lane', sa.SmallInteger(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_slot', name='uq_match_player_slot')
    )
    op.create_index('ix_match_players_steam_id', 'match_players', ['steam_id'], unique=False)
    op.create_table('parsed_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('game_time_secs', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('player_slot', sa.SmallInteger(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parsed_events_match_tick', 'parsed_events', ['match_id', 'tick'], unique=False)
    op.create_index('ix_parsed_events_match_type', 'parsed_events', ['match_id', 'event_type'], unique=False)
    op.create_table('player_state_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_slot', sa.SmallInteger(), nullable=False),
    sa.Column('game_time_secs', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mana', sa.Integer(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_match_player_time', 'player_state_snapshots', ['match_id', 'player_slot', 'game_time_secs'], unique=False)
    op.create_table('replay_files',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('analysis_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('detector_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('game_time_secs', sa.Float(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['match_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_findings')
    op.drop_table('replay_files')
    op.drop_index('ix_snapshots_match_player_time', table_name='player_state_snapshots')
    op.drop_table('player_state_snapshots')
    op.drop_index('ix_parsed_events_match_type', table_name='parsed_events')
    op.drop_index('ix_parsed_events_match_tick', table_name='parsed_events')
    op.drop_table('parsed_events')
    op.drop_index('ix_match_players_steam_id', table_name='match_players')
    op.drop_table('match_players')
    op.drop_table('match_analyses')
    op.drop_table('matches')
    op.drop_table('hero_baselines')
    op.drop_table('users')
    op.drop_table('patches')
    # ### end Alembic commands ###
